Nintendo Music URLs
hsmusic/hsmusic-data pull request #638
Opened 2024-12-18 20:40 UTC by PhantomRuby

Adds URLs to Nintendo Music on applicable songs.

+ minor fixes

2024-12-18 20:41 UTC, PhantomRuby commented
still need to add Pokemon, but that's gonna be quite the undertaking

2024-12-18 22:16 UTC, leo60228 commented on album/pokemon-scarlet-violet-super-music-collection.yaml
> +- https://m.nintendo.com/share/US/tracks/199248e3-1367-4095-b83c-f0e11c7038b8
```suggestion
- https://m.nintendo.com/shared/US/tracks/199248e3-1367-4095-b83c-f0e11c7038b8
```

2024-12-18 22:17 UTC, leo60228 requested changes
URLs all look correct otherwise

2024-12-18 22:17 UTC, leo60228 commented on album/pokemon-scarlet-violet-super-music-collection.yaml
> +- https://m.nintendo.com/share/US/tracks/199248e3-1367-4095-b83c-f0e11c7038b8
```suggestion
- https://m.nintendo.com/shared/US/tracks/199248e3-1367-4095-b83c-f0e11c7038b8
```

2024-12-18 22:17 UTC, leo60228 commented on album/pokemon-scarlet-violet-super-music-collection.yaml
> +- https://m.nintendo.com/shared//US/tracks/62b941f5-7c93-4d14-b577-a65507c83053
```suggestion
- https://m.nintendo.com/shared/US/tracks/62b941f5-7c93-4d14-b577-a65507c83053
```

2024-12-19 02:15 UTC, leo60228 approved these changes

2024-12-28 20:00 UTC, merged